//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoAlimentar
    {
        public int idRegisto { get; set; }
        public int fk_idInstituicao { get; set; }
        public int fk_idBeneficiario { get; set; }
    
        public virtual Beneficiario Beneficiario { get; set; }
        public virtual Instituicao Instituicao { get; set; }
    }
}
