//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        private Beneficiario beneficiario;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiario()
        {
            this.BancoAlimentar = new HashSet<BancoAlimentar>();
        }

        public Beneficiario(Beneficiario beneficiario)
        {
            this.beneficiario = beneficiario;
        }

        public int idBeneficiario { get; set; }
        public string nomeBeneficiario { get; set; }
        public int nifBeneficiario { get; set; }
        public int biBeneficiario { get; set; }
        public int telefoneBeneficiario { get; set; }
        public int fk_idFamilia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoAlimentar> BancoAlimentar { get; set; }
        public virtual Familia Familia { get; set; }
    }
}
