//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
        }
    
        public int Id { get; set; }
        [Display(Name="Nome da familia")]
        public string Nome { get; set; }
        [Display(Name = "Nome do responsável")]
        public string NomeResponsavel { get; set; }
        [Display(Name = "Telefone do responsável")]
        //[MaxLength(9)] [MinLength(9)]
        public int TelefoneResponsavel { get; set; }
        [Display(Name = "NIF do responsável")]
        public int NIFResponsavel { get; set; }
        [Display(Name = "BI do responsável")]
        public int BIResponsavel { get; set; }
        [Display(Name = "Numero de membros")]
        [Range(0, 40)]
        public int NumeroMembros { get; set; }
        [Display(Name = "ID da instituição")]
        public int IdInstituicao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual Instituicao Instituicao { get; set; }
    }
}
