//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
        }
    
        public int idFamilia { get; set; }
        public string nomeFamilia { get; set; }
        public string nomeResponsavel { get; set; }
        public string telefoneResponsavel { get; set; }
        public int nifResponsavel { get; set; }
        public int biResponsavel { get; set; }
        public int numeroMembros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
    }
}
