//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeResponsavel { get; set; }
        public int TelefoneResponsavel { get; set; }
        public int NIFResponsavel { get; set; }
        public int BIResponsavel { get; set; }
        public int NumeroMembros { get; set; }
        public int IdInstituicao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual Instituicao Instituicao { get; set; }
    }
}
