//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtribuicaoCabazesipps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituicao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instituicao()
        {
            this.BancoAlimentar = new HashSet<BancoAlimentar>();
        }
    
        public int idInstituicao { get; set; }
        public string nomeInstituicao { get; set; }
        public int nifInstituicao { get; set; }
        public int telefoneInstituicao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoAlimentar> BancoAlimentar { get; set; }
    }
}
